services:
  # web:
  #   container_name: web
  #   build: .
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_HOST=db
  #   command: >
  #     bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
  #   depends_on:
  #     - db

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  # db_test:
  #   container_name: "test_db"
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=HEADMAN_TEST_DB
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - test_db:/var/lib/postgresql/data


volumes:
  db:
    driver: local

  test_db:
    driver: local
    

